# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Orr's Apples
tagline:             'Better than horse chestnuts'
description:         'I have things to say.'
url:                 http://majormajormajormajor.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Major M. Major
  url:               https://github.com/kayvingt/kayvingt.github.io
  email:             kayvingt@gmail.com

# Custom vars

