# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Please Here Land Here Please
tagline:             'A Place Thing'
description:         'This is here.'
url:                 http://majormajormajormajor.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Major M. Major
  url:               http://majormajormajormajor.com
  email:             kayvingt@gmail.com

# Custom vars
version:             1.0.0
